### ISSUE TITLE
Briefcase spawning

### ISSUE THREAD

**Issue by matthewmcpartland** [sammyholt/edu.cpp.cs.cs141.FinalProject#21]
I haven't had the chance to check the code yet, if I finish my portion in time I will try to find the source of this bug

Briefcase spawning works most of the time, but it sometimes fails. On occasion it will spawn no briefcases or two briefcases. This is a bit game breaking as it can prevent someone from winning. I have not noticed it to spawn 3 briefcases, the maximum has always been 2.

Below will be two examples of each happening

 [ * ]  [ * ]  [ D ]  [ * ]  [ N ]  [ * ]  [ * ]  [ * ]  [ N ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ N ]  [ * ]  [ * ] 
 [ U ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ N ]  [ * ]  [ R ]  [ N ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ N ]  [ I ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ P ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 

example 2, with two briefcases spawned
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ N ]  [ * ] 
 [ * ]  [ B ]  [ * ]  [ N ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ N ]  [ * ]  [ N ]  [ * ]  [ * ] 
 [ * ]  [ D ]  [ * ]  [ I ]  [ * ]  [ * ]  [ * ]  [ * ]  [ N ] 
 [ * ]  [ B ]  [ * ]  [ * ]  [ R ]  [ N ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ U ] 
 [ P ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]

**Comment by sammyholt** [comment]
I think this is an issue with the display because I was able to replicate both of your examples after a few tries and I ran my method that returns the room number with the briefcase and each time it only returned one of the rooms.  The way I wrote that method, it would return the highest index of the briefcase it found because it simply loops through the rooms and assigns the return int variable to the current index of the array if it finds the briefcase.  In your example 2, it would have returned 6 if it was a problem with actual generation, but instead it returned 3:

P = Player, R = Room, N = Ninja, B = Room w/ Briefcase, D = Radar, U = Bullet, I = Invincibility
 [ D ]  [ I ]  [ \* ]  [ \* ]  [ \* ]  [ N ]  [ \* ]  [ \* ]  [ N ] 
 [ \* ]  [ B ]  [ \* ]  [ \* ]  [ R ]  [ \* ]  [ \* ]  [ R ]  [ \* ] 
 [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ] 
 [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ N ]  [ \* ]  [ \* ]  [ N ]  [ \* ] 
 [ \* ]  [ B ]  [ \* ]  [ \* ]  [ R ]  [ U ]  [ \* ]  [ R ]  [ \* ] 
 [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ N ]  [ \* ]  [ N ]  [ \* ] 
 [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ] 
 [ \* ]  [ R ]  [ \* ]  [ \* ]  [ R ]  [ \* ]  [ \* ]  [ R ]  [ \* ] 
 [ P ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ]  [ \* ] 

Briefcase room number: 3

It must just be a display bug, so I will look into that.  It shouldn't be affecting the actual game logic at all, just the visual representation of the board,

**Comment by sammyholt** [comment]
I generated 100 grids, and when the briefcase is at index 3, it also shows as being at index 6.  When it is at index 8, it does not show at all.

**Comment by sammyholt** [comment]
Addressed by commit 1267d7cbd5924ead28fc9ae8b1a30dae5830123c
